apiVersion: v1
kind: Service
metadata:
  name: {{ include "vacation-planner.fullname" . }}-backend
  labels:
    {{- include "vacation-planner.backendLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vacation-planner.backendSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vacation-planner.fullname" . }}
  labels:
    {{- include "vacation-planner.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vacation-planner.frontendSelectorLabels" . | nindent 4 }}
